### ISSUE TITLE
fix possibly infinite recursion in AvatarBackground

### ISSUE THREAD

**Issue by phivk** [phivk/fitz-hayley-1#22]

**Comment by alexabruck** [comment]
I think the right solution is to make the Avatars smaller, because we actually want to fit them to the (smaller) screen

**Comment by phivk** [comment]
That might be nice too. I do think we need less Avatars on small screens...

**Comment by phivk** [comment]
closed via https://github.com/phivk/fitz-hayley/commit/2c9934bc79fa038fad70e136cf1121d08b0c4a25
